<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>TibbiNav.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TibbiNav.Domain\TibbiNav.Domain.csproj" />
    <ProjectReference Include="..\TibbiNav.Infrastructure\TibbiNav.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="QuestPDF" Version="2026.7.3" />
  </ItemGroup>
</Project>
